name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # Lägg till API-nyckeln här

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mainricko/myapp:${{ github.sha }} -t mainricko/myapp:latest .

      - name: Push Docker Image with Git SHA tag
        run: docker push mainricko/myapp:${{ github.sha }}

      - name: Push Docker Image with Latest Tag
        run: docker push mainricko/myapp:latest
