name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build_and_push_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t mainricko/myapp:${{ github.sha }} .
          docker push myusername/myapp:${{ github.sha }}
