name: Python Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      log_error:
        description: 'Generate log file on test failure'
        required: true
        default: 'false'
        type: boolean

jobs:
  run_tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: "info" 

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: test_step
        run: |
          pytest tests/ --log-cli-level=${{ env.LOG_LEVEL }} | tee pytest.log
        continue-on-error: true  # let it run even when failed

      - name: Upload error log
        if: ${{ failure() && github.event.inputs.log_error == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: pytest.log
